name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15.x
      - uses: actions/checkout@v1
      - name: build
        run: |
          go mod init
          go build -o kv2get -v cmd/kv2env/main.go
